/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include<stdio.h>

#define RCC_BASE_ADDR	 	 0x40023800UL
#define RCC_CFGR_OFFSET	 	 0x08UL
#define RCC_CFGR_ADDR	 	 (RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define RCC_AHB1ENR_OFFSET   0x30UL
#define RCC_AHB1ENR_ADDR 	 (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

#define GPIOA_BASE_ADDR		 0x40020000UL
#define GPIOA_MODER_OFFSET	 0x00UL
#define GPIOA_MODER_ADDR	 (GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)

#define GPIOA_AFRH_OFFSET	 0x24UL
#define GPIOA_AFRH_ADDR		 (GPIOA_BASE_ADDR + GPIOA_AFRH_OFFSET)

int main(void)
{
	uint32_t *pRccCfgr = (uint32_t *) RCC_CFGR_ADDR;

	//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
	*pRccCfgr &= ~(0x3 << 21); //clear the 21. and 22. bit positions

	//Configure MCO1 prescaler by dividing 4           *********logic analyzer da gözlemleyebilmek için
	*pRccCfgr |= ( 1 << 25);
	*pRccCfgr |= ( 1 << 26);

	//2. Configure PA8 to AF0 mode to behave as MCO1 signal

	//a) Enable the perip clock for GPIOA perip
	uint32_t *pRccAhb1Enr = (uint32_t *)RCC_AHB1ENR_ADDR;
	*pRccAhb1Enr |= (1 << 0);

	//b) Configure the mode of GPIOA pin for 8 as alternate function
	uint32_t *pGpioaModer = (uint32_t *)GPIOA_MODER_ADDR;
	*pGpioaModer &= ~(0x3 << 16); //clear
	*pGpioaModer |= (0x2 << 16); //set

	//c) Configure the alternate func reg to set the mode 0 for PA8
	uint32_t *pGpioaAfrh = (uint32_t *)GPIOA_AFRH_ADDR;
	*pGpioaAfrh &= ~(0xf << 0);

    /* Loop forever */
	for(;;);
}










